default_language_version:
  python: python3

repos:
  - repo: local
    hooks:
      - id: pytest
        name: Run pytest before commit
        entry: python -m pytest -v
        language: system
        types: [python]
        pass_filenames: false
