# -----------------------------
# Netlify configuration for Project Indexly
# -----------------------------

[build]
  base = "docs"              # Hugo site root
  publish = "public"         # Folder inside base to deploy
  command = "hugo -e production"  # Use production environment

[context.production.environment]
  HUGO_VERSION = "0.148.1"
  HUGO_EXTENDED = "true"

[build.environment]
  # Cache Hugo resources to speed up builds
  HUGO_CACHEDIR = "/tmp/hugo_cache"
  HUGO_ENVIRONMENT = "production"

# -----------------------------
# Ignore unnecessary folders for clean builds
# -----------------------------
[[ignore]]
  paths = [
    "docs/node_modules",
    "dist",
    "*.log"
  ]
