[pytest]
filterwarnings =
    ignore:.*SwigPy.*:DeprecationWarning
    ignore:.*swigvarlink.*:DeprecationWarning
    ignore:.*PyPDF2.*:DeprecationWarning
addopts = --strict-markers
norecursedirs =
    .git
    .pytest_cache
    .venv
    .venv-indexly
    build
    dist
    docs
    node_modules
    pytest-cache-files-*
    test-tmp
    tmp-doctor-*
markers =
    asyncio: mark test as asyncio coroutine (requires pytest-asyncio)
