name: CI - Indexly Tests

on:
  push:
    branches: [main, staging, wip/**]
    paths-ignore:
      - "docs/**"
      - "public/**"
  pull_request:
    branches: [main, staging]

jobs:
  test:
    name: Run Pytest
    runs-on: ubuntu-latest   # ✅ faster & better for Python CI

    strategy:
      matrix:
        python-version: [3.13]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies (CI lean set)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-ci.txt
          pip install -e .

      - name: Run Pytest
        run: |
          python -m pytest -v tests/ --maxfail=5 --disable-warnings

      - name: Upload pytest results (optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-results
          path: .pytest_cache/
